# Generated by Django 3.1.3 on 2021-04-08 06:41

from django.db import migrations, models
import suit.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0013_auto_20201112_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Text',
            },
        ),
        migrations.AddField(
            model_name='showcase',
            name='stream',
            field=suit.fields.StreamField(blank=True, default='[]', verbose_name='Content blocks (based on streamfield)'),
        ),
    ]
